
milk_productio_cow_per_day = "SELECT m.cow_id, sum(m.value) as milk_liters FROM measurements m INNER JOIN sensors s ON s.id = m.sensor_id WHERE s.unit = 'L' AND DATE(m.timestamp, 'unixepoch') = ? GROUP BY m.cow_id"

cow_weight_comparation = '''WITH MAX_DATE_COW AS (SELECT M.COW_ID, MAX(M.TIMESTAMP) AS TIMESTAMP FROM MEASUREMENTS M INNER JOIN SENSORS S ON M.SENSOR_ID = S.ID WHERE S.UNIT = 'kg' AND M.VALUE > 0 GROUP BY M.COW_ID),
    AVERAGE_WEIGHT AS (SELECT M.COW_ID, AVG(M.VALUE) AS AVG_WEIGHT FROM MEASUREMENTS M INNER JOIN SENSORS S ON M.SENSOR_ID = S.ID INNER JOIN MAX_DATE_COW MDC ON M.COW_ID = MDC.COW_ID WHERE M.VALUE > 0 AND S.UNIT = 'kg' AND DATE(M.TIMESTAMP,'unixepoch') > DATE(DATE(MDC.TIMESTAMP,'unixepoch'),'-30 day') GROUP BY M.COW_ID)
    SELECT M.COW_ID, M.VALUE AS CURRENT_WEIGHT, AW.AVG_WEIGHT AVG_WEIGHT_LAST_30_DAYS, DATE(MDC.TIMESTAMP,'unixepoch') AS CURRENT_DATE FROM MEASUREMENTS M INNER JOIN MAX_DATE_COW MDC ON M.COW_ID = MDC.COW_ID AND M.TIMESTAMP = MDC.TIMESTAMP INNER JOIN AVERAGE_WEIGHT AW ON M.COW_ID = AW.COW_ID INNER JOIN SENSORS S ON M.SENSOR_ID = S.ID WHERE S.UNIT = 'kg'
    '''

cow_could_be_sick = '''WITH WEIGHT_DATA AS (
    WITH MAX_DATE_COW AS (SELECT M.COW_ID, MAX(M.TIMESTAMP) AS TIMESTAMP FROM MEASUREMENTS M INNER JOIN SENSORS S ON M.SENSOR_ID = S.ID WHERE S.UNIT = 'kg' AND M.VALUE > 0 GROUP BY M.COW_ID),
    AVERAGE_WEIGHT AS (SELECT M.COW_ID, AVG(M.VALUE) AS AVG_WEIGHT FROM MEASUREMENTS M INNER JOIN SENSORS S ON M.SENSOR_ID = S.ID INNER JOIN MAX_DATE_COW MDC ON M.COW_ID = MDC.COW_ID WHERE M.VALUE > 0 AND S.UNIT = 'kg' AND DATE(M.TIMESTAMP,'unixepoch') > DATE(DATE(MDC.TIMESTAMP,'unixepoch'),'-30 day') GROUP BY M.COW_ID)
    SELECT M.COW_ID, M.VALUE AS LAST_WEIGHT, AW.AVG_WEIGHT AS AVG_WEIGHT_LAST_30_DAYS, DATE(MDC.TIMESTAMP,'unixepoch') AS LAST_DATE FROM MEASUREMENTS M INNER JOIN MAX_DATE_COW MDC ON M.COW_ID = MDC.COW_ID AND M.TIMESTAMP = MDC.TIMESTAMP INNER JOIN AVERAGE_WEIGHT AW ON M.COW_ID = AW.COW_ID INNER JOIN SENSORS S ON M.SENSOR_ID = S.ID WHERE S.UNIT = 'kg'
    )
    SELECT COW_ID, LAST_WEIGHT, AVG_WEIGHT_LAST_30_DAYS, (AVG_WEIGHT_LAST_30_DAYS - LAST_WEIGHT) AS DIFF_WEIGHT, LAST_DATE FROM WEIGHT_DATA WHERE (AVG_WEIGHT_LAST_30_DAYS - LAST_WEIGHT) > 6'''

cow_last_datetime_measurements = '''SELECT DATETIME(MAX(timestamp), 'unixepoch') as timestamp FROM measurements where cow_id = ?'''

cow_measurements_last_30_days_compare_last_datetime = '''SELECT c.id as cow_id, c.name as cow_name, DATETIME(m.timestamp, 'unixepoch') as timestamp, m.value, s.unit FROM cows c inner join measurements m on c.id = m.cow_id inner join sensors s on m.sensor_id = s.id where c.id = ? AND DATETIME(m.timestamp, 'unixepoch') > DATETIME(?, '-30 day') ORDER BY 3 DESC'''